// APMU standalone file list (sim variant) -- paths relative to apmu_standalone/
// Order is dependency-correct (taken from the he-soc Bender-generated compile scripts).
+incdir+rtl/axi/include
+incdir+rtl/common_cells/include
+incdir+rtl/ibex_pmu/rtl
+incdir+rtl/ibex_pmu/vendor/lowrisc_ip/ip/prim/rtl
rtl/tech_cells_generic/src/rtl/tc_sram.sv
rtl/tech_cells_generic/src/rtl/tc_clk.sv
rtl/common_cells/src/cf_math_pkg.sv
rtl/common_cells/src/delta_counter.sv
rtl/common_cells/src/fifo_v3.sv
rtl/common_cells/src/rr_arb_tree.sv
rtl/common_cells/src/spill_register_flushable.sv
rtl/common_cells/src/addr_decode_dync.sv
rtl/common_cells/src/addr_decode.sv
rtl/common_cells/src/counter.sv
rtl/common_cells/src/lzc.sv
rtl/common_cells/src/spill_register.sv
rtl/common_cells/src/stream_register.sv
rtl/axi/src/axi_pkg.sv
rtl/axi/src/axi_atop_filter.sv
rtl/axi/src/axi_lite_demux.sv
rtl/axi/src/axi_lite_from_mem.sv
rtl/axi/src/axi_lite_mux.sv
rtl/axi/src/axi_lite_regs.sv
rtl/axi/src/axi_lite_to_axi.sv
rtl/axi/src/axi_err_slv.sv
rtl/axi/src/axi_lite_xbar.sv
rtl/ibex_pmu/rtl/ibex_pkg.sv
rtl/ibex_pmu/rtl/ibex_register_file_ff.sv
rtl/ibex_pmu/rtl/ibex_alu.sv
rtl/ibex_pmu/rtl/ibex_compressed_decoder.sv
rtl/ibex_pmu/rtl/ibex_controller.sv
rtl/ibex_pmu/rtl/ibex_counter.sv
rtl/ibex_pmu/rtl/ibex_csr.sv
rtl/ibex_pmu/rtl/ibex_decoder.sv
rtl/ibex_pmu/rtl/ibex_fetch_fifo.sv
rtl/ibex_pmu/rtl/ibex_load_store_unit.sv
rtl/ibex_pmu/rtl/ibex_multdiv_fast.sv
rtl/ibex_pmu/rtl/ibex_multdiv_slow.sv
rtl/ibex_pmu/rtl/ibex_pmp.sv
rtl/ibex_pmu/rtl/ibex_pmu_counter.sv
rtl/ibex_pmu/rtl/ibex_wb_stage.sv
rtl/ibex_pmu/rtl/ibex_cs_registers.sv
rtl/ibex_pmu/rtl/ibex_ex_block.sv
rtl/ibex_pmu/rtl/ibex_id_stage.sv
rtl/ibex_pmu/rtl/ibex_prefetch_buffer.sv
rtl/ibex_pmu/rtl/ibex_if_stage.sv
rtl/ibex_pmu/rtl/ibex_core.sv
rtl/apmu/src/pmu_pkg.sv
rtl/apmu/src/pmu_port.sv
rtl/apmu/src/pmu_ispm.sv
rtl/apmu/src/pmu_dspm.sv
rtl/apmu/src/pmu_counter.sv
rtl/apmu/src/pmu_core.sv
rtl/apmu/src/pmu_port_wrap.sv
rtl/apmu/src/pmu_top.sv
rtl/ibex_pmu/rtl/ibex_register_file_fpga.sv
rtl/ibex_pmu/rtl/ibex_register_file_latch.sv
rtl/hesoc_cfg/apmu_hesoc_top.sv
